# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mandarsadye/Desktop/Assignment3/RACE_TRACK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mandarsadye/Desktop/Assignment3/RACE_TRACK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mandarsadye/Desktop/Assignment3/RACE_TRACK/CMakeFiles /home/mandarsadye/Desktop/Assignment3/RACE_TRACK/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mandarsadye/Desktop/Assignment3/RACE_TRACK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clean_all

# Build rule for target.
clean_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_all
.PHONY : clean_all

# fast build rule for target.
clean_all/fast:
	$(MAKE) -f CMakeFiles/clean_all.dir/build.make CMakeFiles/clean_all.dir/build
.PHONY : clean_all/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named RaceTrack

# Build rule for target.
RaceTrack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RaceTrack
.PHONY : RaceTrack

# fast build rule for target.
RaceTrack/fast:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/build
.PHONY : RaceTrack/fast

Application.o: Application.cpp.o

.PHONY : Application.o

# target to build an object file
Application.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/Application.cpp.o
.PHONY : Application.cpp.o

Application.i: Application.cpp.i

.PHONY : Application.i

# target to preprocess a source file
Application.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/Application.cpp.i
.PHONY : Application.cpp.i

Application.s: Application.cpp.s

.PHONY : Application.s

# target to generate assembly for a file
Application.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/Application.cpp.s
.PHONY : Application.cpp.s

lib/src/IndexBuffer.o: lib/src/IndexBuffer.cpp.o

.PHONY : lib/src/IndexBuffer.o

# target to build an object file
lib/src/IndexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/IndexBuffer.cpp.o
.PHONY : lib/src/IndexBuffer.cpp.o

lib/src/IndexBuffer.i: lib/src/IndexBuffer.cpp.i

.PHONY : lib/src/IndexBuffer.i

# target to preprocess a source file
lib/src/IndexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/IndexBuffer.cpp.i
.PHONY : lib/src/IndexBuffer.cpp.i

lib/src/IndexBuffer.s: lib/src/IndexBuffer.cpp.s

.PHONY : lib/src/IndexBuffer.s

# target to generate assembly for a file
lib/src/IndexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/IndexBuffer.cpp.s
.PHONY : lib/src/IndexBuffer.cpp.s

lib/src/Renderer.o: lib/src/Renderer.cpp.o

.PHONY : lib/src/Renderer.o

# target to build an object file
lib/src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/Renderer.cpp.o
.PHONY : lib/src/Renderer.cpp.o

lib/src/Renderer.i: lib/src/Renderer.cpp.i

.PHONY : lib/src/Renderer.i

# target to preprocess a source file
lib/src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/Renderer.cpp.i
.PHONY : lib/src/Renderer.cpp.i

lib/src/Renderer.s: lib/src/Renderer.cpp.s

.PHONY : lib/src/Renderer.s

# target to generate assembly for a file
lib/src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/Renderer.cpp.s
.PHONY : lib/src/Renderer.cpp.s

lib/src/Shader.o: lib/src/Shader.cpp.o

.PHONY : lib/src/Shader.o

# target to build an object file
lib/src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/Shader.cpp.o
.PHONY : lib/src/Shader.cpp.o

lib/src/Shader.i: lib/src/Shader.cpp.i

.PHONY : lib/src/Shader.i

# target to preprocess a source file
lib/src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/Shader.cpp.i
.PHONY : lib/src/Shader.cpp.i

lib/src/Shader.s: lib/src/Shader.cpp.s

.PHONY : lib/src/Shader.s

# target to generate assembly for a file
lib/src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/Shader.cpp.s
.PHONY : lib/src/Shader.cpp.s

lib/src/Texture.o: lib/src/Texture.cpp.o

.PHONY : lib/src/Texture.o

# target to build an object file
lib/src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/Texture.cpp.o
.PHONY : lib/src/Texture.cpp.o

lib/src/Texture.i: lib/src/Texture.cpp.i

.PHONY : lib/src/Texture.i

# target to preprocess a source file
lib/src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/Texture.cpp.i
.PHONY : lib/src/Texture.cpp.i

lib/src/Texture.s: lib/src/Texture.cpp.s

.PHONY : lib/src/Texture.s

# target to generate assembly for a file
lib/src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/Texture.cpp.s
.PHONY : lib/src/Texture.cpp.s

lib/src/VertexArray.o: lib/src/VertexArray.cpp.o

.PHONY : lib/src/VertexArray.o

# target to build an object file
lib/src/VertexArray.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/VertexArray.cpp.o
.PHONY : lib/src/VertexArray.cpp.o

lib/src/VertexArray.i: lib/src/VertexArray.cpp.i

.PHONY : lib/src/VertexArray.i

# target to preprocess a source file
lib/src/VertexArray.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/VertexArray.cpp.i
.PHONY : lib/src/VertexArray.cpp.i

lib/src/VertexArray.s: lib/src/VertexArray.cpp.s

.PHONY : lib/src/VertexArray.s

# target to generate assembly for a file
lib/src/VertexArray.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/VertexArray.cpp.s
.PHONY : lib/src/VertexArray.cpp.s

lib/src/VertexBuffer.o: lib/src/VertexBuffer.cpp.o

.PHONY : lib/src/VertexBuffer.o

# target to build an object file
lib/src/VertexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/VertexBuffer.cpp.o
.PHONY : lib/src/VertexBuffer.cpp.o

lib/src/VertexBuffer.i: lib/src/VertexBuffer.cpp.i

.PHONY : lib/src/VertexBuffer.i

# target to preprocess a source file
lib/src/VertexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/VertexBuffer.cpp.i
.PHONY : lib/src/VertexBuffer.cpp.i

lib/src/VertexBuffer.s: lib/src/VertexBuffer.cpp.s

.PHONY : lib/src/VertexBuffer.s

# target to generate assembly for a file
lib/src/VertexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/src/VertexBuffer.cpp.s
.PHONY : lib/src/VertexBuffer.cpp.s

lib/vendor_src/stb_image.o: lib/vendor_src/stb_image.cpp.o

.PHONY : lib/vendor_src/stb_image.o

# target to build an object file
lib/vendor_src/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/vendor_src/stb_image.cpp.o
.PHONY : lib/vendor_src/stb_image.cpp.o

lib/vendor_src/stb_image.i: lib/vendor_src/stb_image.cpp.i

.PHONY : lib/vendor_src/stb_image.i

# target to preprocess a source file
lib/vendor_src/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/vendor_src/stb_image.cpp.i
.PHONY : lib/vendor_src/stb_image.cpp.i

lib/vendor_src/stb_image.s: lib/vendor_src/stb_image.cpp.s

.PHONY : lib/vendor_src/stb_image.s

# target to generate assembly for a file
lib/vendor_src/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/lib/vendor_src/stb_image.cpp.s
.PHONY : lib/vendor_src/stb_image.cpp.s

models/src/camera.o: models/src/camera.cpp.o

.PHONY : models/src/camera.o

# target to build an object file
models/src/camera.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/models/src/camera.cpp.o
.PHONY : models/src/camera.cpp.o

models/src/camera.i: models/src/camera.cpp.i

.PHONY : models/src/camera.i

# target to preprocess a source file
models/src/camera.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/models/src/camera.cpp.i
.PHONY : models/src/camera.cpp.i

models/src/camera.s: models/src/camera.cpp.s

.PHONY : models/src/camera.s

# target to generate assembly for a file
models/src/camera.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/models/src/camera.cpp.s
.PHONY : models/src/camera.cpp.s

models/src/node.o: models/src/node.cpp.o

.PHONY : models/src/node.o

# target to build an object file
models/src/node.cpp.o:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/models/src/node.cpp.o
.PHONY : models/src/node.cpp.o

models/src/node.i: models/src/node.cpp.i

.PHONY : models/src/node.i

# target to preprocess a source file
models/src/node.cpp.i:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/models/src/node.cpp.i
.PHONY : models/src/node.cpp.i

models/src/node.s: models/src/node.cpp.s

.PHONY : models/src/node.s

# target to generate assembly for a file
models/src/node.cpp.s:
	$(MAKE) -f CMakeFiles/RaceTrack.dir/build.make CMakeFiles/RaceTrack.dir/models/src/node.cpp.s
.PHONY : models/src/node.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... clean_all"
	@echo "... run"
	@echo "... RaceTrack"
	@echo "... Application.o"
	@echo "... Application.i"
	@echo "... Application.s"
	@echo "... lib/src/IndexBuffer.o"
	@echo "... lib/src/IndexBuffer.i"
	@echo "... lib/src/IndexBuffer.s"
	@echo "... lib/src/Renderer.o"
	@echo "... lib/src/Renderer.i"
	@echo "... lib/src/Renderer.s"
	@echo "... lib/src/Shader.o"
	@echo "... lib/src/Shader.i"
	@echo "... lib/src/Shader.s"
	@echo "... lib/src/Texture.o"
	@echo "... lib/src/Texture.i"
	@echo "... lib/src/Texture.s"
	@echo "... lib/src/VertexArray.o"
	@echo "... lib/src/VertexArray.i"
	@echo "... lib/src/VertexArray.s"
	@echo "... lib/src/VertexBuffer.o"
	@echo "... lib/src/VertexBuffer.i"
	@echo "... lib/src/VertexBuffer.s"
	@echo "... lib/vendor_src/stb_image.o"
	@echo "... lib/vendor_src/stb_image.i"
	@echo "... lib/vendor_src/stb_image.s"
	@echo "... models/src/camera.o"
	@echo "... models/src/camera.i"
	@echo "... models/src/camera.s"
	@echo "... models/src/node.o"
	@echo "... models/src/node.i"
	@echo "... models/src/node.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

